apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
 name: csr-for-user4
spec:
 groups:
 - "system:authenticated"
 usages:
 - client auth
 - digital signature
 - key encipherment
 signerName: kubernetes.io/kube-apiserver-client
 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZkWE5sY2pRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFDdE1FTnlYMUxmWmNKUFcvckFFNVBlNjY5aGhGc3hPYkh3bFFCN2hzYmlXdW16CnBEWUpXK05RS3ZlbFBNakxwVzhmZTlUSlhxZDdSbmdqVzV3SXE3UDkwdno0MDRlTlk3OTc2OENNS2F0bmtyMk4KU1hPRVJNS0NhZTdvaU11MHp2UzdwYkJsRzZseXpEdzJWRGQ5d2ZqTjRJc2lHWUdJRTJsSkdmWXQ1bVJEMldRRQpLOUo3RGZvNmFKN3BoWENlalk2SFd2aW83VnlOR24xZ3VYZXBQV3R2a2RwQVZpYzZHejU5a0VYWDg5Y1p2SnpyClR6eFlrdDBQaTRjYUNSN3Z6bDZPQ1ZnU2xaWC9BQm90STZCNlhrS0JuSTZQb2dpK1dhRksyUjBoRVlXSVhnV2cKUTVTcWR6KzdVYkdGUkU2bEg0RmFQc0grdTZhS2JLSjl1bllpZzBwbEFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFkV3IyaWVxZmF3NCtOaThuVVVwRk9JejVHUEx2ZytOMjNHSVcyMkxvRGNyeENyNmVEbldMCjFlaW90djJKdlM4RzBJWHVHaTNrT3YrZEljWUIvckhnSXloT2FpU1BIMEozOVY5UWFhK1p1MHAxb2t0eFhGVmcKUS81QnpZVC9wRkIyVzhic3VRM3ZpUm9DOHc2TElsd0Fod0RCOVpQdFVVLzVSalZLVW5zK3dFcS9Yc2x0S1ZxUQpHcFpRbGRpYjdtb3g5RVIwMXM1YnB1cWJtQ041WDgwUDJ4aXU2S3g2bHFIcE9wS3JXTEtrbmw0MHB4SVJXZUVECjBIdUo1NmlESHpEcFB5NzJRbXJWcFhVRGNrcVBMSGo2aVlMSUF0cXNzaHZlcnFUcTRoSFVPNmt5Qjh6WE1NRmEKQXM5cDJvZWdzdGpTOGRYbS9pTXpuZGJZUjV4Qmxja1kwdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=

